// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfhpljiqqrelkxclmydz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmaHBsamlxcXJlbGt4Y2xteWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjUxNzgsImV4cCI6MjA2NTc0MTE3OH0.v05AvFqN6CziyTnWOFrtzmaxKDDXsE3dre3s1Pho_Tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);